debugging WF - Update ghcr.io/hassio-addons/base-python

diff --git a/.github/workflows/Bump-Addon-Version-base.yml b/.github/workflows/Bump-Addon-Version-base.yml
--- a/.github/workflows/Bump-Addon-Version-base.yml
+++ b/.github/workflows/Bump-Addon-Version-base.yml
@@ -37,10 +37,12 @@ jobs:
           latest_version=$(echo "$response" | grep -oP '"tag_name": "\K[^"]+' | sed -n '1p')
           files=$(find . -name "CHANGELOG.md" -exec grep -l "# Changelog" {} \;)
           
+          echo "Latest version from repo: $latest_version"
           echo "Found files: $files"
+          
           echo "$files" | while IFS= read -r file; do
               current_version=$(grep -oP "^## \K\d+\.\d+\.\d+" "$file" | sort -rV | head -n1)
-              echo "Adding changelog for $file and current version $current_version"
+              echo "Processing $file, current version: $current_version"
           
               if [ -n "$current_version" ]; then
                   IFS='.' read -r major minor patch <<< "$current_version"
@@ -49,14 +51,17 @@ jobs:
                       new_version="$major.$minor.$patch"
                       echo "New version: $new_version"
           
-                      if sed -i "/# Changelog/a \\## $new_version\\n- automatically update addon-base to version $latest_version\\n" "$file"; then
+                      # Debugging the sed command
+                      sed_debug=$(sed "/# Changelog/a \\## $new_version\\n- automatically update addon-base to version $latest_version\\n" "$file" 2>&1)
+                      if [ $? -eq 0 ]; then
                           echo "Added changelog auto text for $file with new version $new_version and addon-base version $latest_version"
                       else
                           echo "Error while writing changelog auto text for $file with new version $new_version and addon-base version $latest_version"
+                          echo "sed command output: $sed_debug"
                           exit 1
                       fi
                   else
-                      echo "Error while increasing $current_version number"
+                      echo "Error while parsing patch version number in $current_version"
                       exit 1
                   fi
               else
@@ -64,8 +69,6 @@ jobs:
                   exit 1
               fi
           done
-
-
       - name: Commit & Push
         uses: actions-js/push@v1.5
         with:
