Try fix wf on Update ghcr.io/hassio-addons/base-python

diff --git a/.github/workflows/Bump-Addon-Version-base.yml b/.github/workflows/Bump-Addon-Version-base.yml
--- a/.github/workflows/Bump-Addon-Version-base.yml
+++ b/.github/workflows/Bump-Addon-Version-base.yml
@@ -36,29 +36,35 @@ jobs:
           response=$(curl -s "$repo_url/releases")
           latest_version=$(echo "$response" | grep -oP '"tag_name": "\K[^"]+' | sed -n '1p')
           files=$(find . -name "CHANGELOG.md" -exec grep -l "# Changelog" {} \;)
-
+          
+          echo "Found files: $files"
           echo "$files" | while IFS= read -r file; do
               current_version=$(grep -oP "^## \K\d+\.\d+\.\d+" "$file" | sort -rV | head -n1)
               echo "Adding changelog for $file and current version $current_version"
-
+          
               if [ -n "$current_version" ]; then
                   IFS='.' read -r major minor patch <<< "$current_version"
                   if [ -n "$patch" ]; then
-                    ((patch++))
-                    new_version="$major.$minor.$patch"
-
-                    if sed -i "/# Changelog/a \\## $new_version\\n- automatically update addon-base to version $latest_version\n" "$file"; then
-                        echo "Added changelog auto text for $file with new version $new_version and addon-base version $latest_version"
-                    else
-                        echo "Error while writing changelog auto text for $file with new version $new_version and addon-base version $latest_version"
-                    fi
+                      ((patch++))
+                      new_version="$major.$minor.$patch"
+                      echo "New version: $new_version"
+          
+                      if sed -i "/# Changelog/a \\## $new_version\\n- automatically update addon-base to version $latest_version\\n" "$file"; then
+                          echo "Added changelog auto text for $file with new version $new_version and addon-base version $latest_version"
+                      else
+                          echo "Error while writing changelog auto text for $file with new version $new_version and addon-base version $latest_version"
+                          exit 1
+                      fi
                   else
-                    echo "Error while increasing $current_version number"
+                      echo "Error while increasing $current_version number"
+                      exit 1
                   fi
               else
                   echo "No valid version found in $file"
+                  exit 1
               fi
           done
+
 
       - name: Commit & Push
         uses: actions-js/push@v1.5
